name: hemloc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - awscli=1.18.2
  - bcrypt=3.1.7
  - boto3=1.12.0
  - botocore=1.15.2
  - ca-certificates=2019.11.28
  - cached-property=1.5.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - colorama=0.4.3
  - cryptography=2.8
  - docker-compose=1.25.4
  - docker-py=4.2.0
  - docker-pycreds=0.4.0
  - dockerpty=0.4.1
  - docopt=0.6.2
  - docutils=0.15.2
  - fabric=2.5.0
  - idna=2.7
  - importlib-metadata=1.5.0
  - importlib_metadata=1.5.0
  - invoke=1.4.1
  - jmespath=0.9.4
  - jsonschema=3.2.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.2.0
  - ncurses=6.1
  - numpy=1.18.1
  - openssl=1.1.1e
  - packaging=20.1
  - paramiko=2.7.1
  - pip=20.0.2
  - protobuf=3.11.4
  - protobuf3-to-dict=0.1.5
  - pyasn1=0.4.8
  - pycparser=2.20
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pyyaml=5.2
  - readline=8.0
  - requests=2.20.1
  - rsa=3.4.2
  - s3transfer=0.3.3
  - sagemaker-python-sdk=1.43.5
  - scipy=1.4.1
  - setuptools=46.1.1
  - six=1.14.0
  - sqlite=3.30.1
  - texttable=1.6.2
  - tk=8.6.10
  - urllib3=1.23
  - websocket-client=0.57.0
  - wheel=0.34.2
  - xz=5.2.4
  - yaml=0.2.2
  - zipp=3.1.0
  - zlib=1.2.11

