AWSTemplateFormatVersion: 2010-09-09

Description: Deploy a model at Sagemaker

Parameters:

  Prefix:
    Type: String
    Default: dev

  TrainJobId:
    Type: String
    Description: Id of the Codepipeline + SagemakerJobs
    
Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      model: !Sub mlops-model-${TrainJobId}
      PrimaryContainer:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Prefix}-ecr-repo:latest
        ModelDataUrl: !Sub s3://sagemaker-${AWS::Region}-${AWS::AccountId}/model/mlops-model-${TrainJobId}/output/model.tar.gz
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/MLOps
  
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
      - InitialInstanceCount: 1
        InitialVariantWeight: 1.0
        InstanceType: ml.t2.medium 
        model: !GetAtt Model.model
        VariantName: !GetAtt Model.model
          
      EndpointConfigName: !Sub mlops-ec-model-dev-${TrainJobId}
      Tags:
        - Key: Name
          Value: !Sub mlops-ec-model-dev-${TrainJobId}
    DependsOn: Model

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub mlops-model-dev-${TrainJobId}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      Tags:
        - Key: Name
          Value: !Sub mlops-model-dev-${TrainJobId}
    DependsOn: EndpointConfig