AWSTemplateFormatVersion: 2010-09-09

Resources:

    DevCFTemplates:
        Type: AWS::S3::Bucket
        Properties: 
          BucketName: !Sub dev-s3-pipeline-artifact
          AccessControl: Private
          VersioningConfiguration:
            Status: Enabled

    TestCFTemplates:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub test-s3-pipeline-artifact
            AccessControl: Private
            VersioningConfiguration:
            Status: Enabled

    ProdCFTemplates:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Sub prod-s3-pipeline-artifact
            AccessControl: Private
            VersioningConfiguration:
            Status: Enabled